SmartCambridge/tfc_web

- tfc_web/dashboard/urls.py
- tfc_web/dashboard/views/dashboard.py
- tfc_web/dashboard/views/widgets/station_board.py
- tfc_web/dashboard/views/widgets/weather.py
divide views into subdirectories to have a more clear division of views with different purposes.
> views cleanup

- tfc_web/csn/templates/csn/application.html
- tfc_web/csn/templates/csn/base.html
- tfc_web/templates/base.html
- tfc_web/tfc_web/settings.py
Also removed CSN links from the common template
Closes #57
> CSN redirect fix

- tfc_web/static/smartpanel/smartpanel.js
Becasue this lets me clone the current default layout
> Add a 1x4 widget layout option

- tfc_web/smartpanel/templates/smartpanel/layout.html
- tfc_web/smartpanel/templates/smartpanel/layout_config.html
- tfc_web/smartpanel/templates/smartpanel/layout_config2.html
- tfc_web/smartpanel/templatetags/jsonify.py
- tfc_web/static/smartpanel/widgets/stop_bus_map/stop_bus_map_schema.json
add filter template to solve django not jsonifying pythong dicts when used in the template
Closes #64
> add jsonify

- tfc_web/smartpanel/views/smartpanel.py
> Only add widget js and css if they exist

- tfc_web/static/smartpanel/widgets/README.md
Documenting the current situation, in lieu of a decision.
Closes #61
> Clarify that local requirements are loaded from the widget directory

- redeploy.sh
Added a script that will bring whichever branch of tfc_web is currently
checked out up to date, update any Python requirements, run any database
migrations, and then stop and re-start Gunicorn
Because I'm getting bored doing it by hand
> Created a redeploy script

- tfc_web/smartpanel/templates/smartpanel/design.html
- tfc_web/smartpanel/templates/smartpanel/layout_config.html
- tfc_web/smartpanel/templates/smartpanel/my.html
- tfc_web/smartpanel/urls.py
- tfc_web/smartpanel/views/smartpanel.py
- tfc_web/static/smartpanel/smartpanel.css
- tfc_web/static/smartpanel/smartpanel.js
> Add edit layout design option

- tfc_web/api/aq/serializers.py
- tfc_web/api/aq/urls.py
- tfc_web/api/aq/views.py
- tfc_web/api/parking/serializers.py
- tfc_web/api/parking/views.py
- tfc_web/api/urls.py
- tfc_web/api/util.py
- tfc_web/api/zones/serializers.py
- tfc_web/api/zones/urls.py
- tfc_web/api/zones/views.py
Added Zone and AQ endpoints based on the same structure as the Parking one. Moved some functionality from parking/views.py to util.py for re-use elsewhere.
Also dropped allowing feed_id as a query parameter for any of the endpoints: it's rather obscure, of little value to anyone other than insiders because only they know what feeds are available, and it significantly complicates the code if we are to correctly defend against directory traversal attacks.
> Add Zone and AQ endpoints; misc reorganisation

- tfc_web/transport/api/serializers.py
> Add compatibility with other APIs using lat lng nomenclature

- tfc_web/api/auth_urls.py
- tfc_web/api/urls.py
> enable login using django-allauth in api docs

- tfc_web/transport/api/serializers.py
- tfc_web/transport/api/views.py
- tfc_web/transport/utils/transxchange.py
Reverts ijl20/tfc_web#77
It's not working properly
> Revert "Add bank holidays checks to the APIs when retrieving VehicleJourneys"

- tfc_web/smartpanel/templates/smartpanel/layout_config.html
- tfc_web/static/smartpanel/smartpanel.css
- tfc_web/static/smartpanel/smartpanel.js
- tfc_web/static/smartpanel/widget_config.js
- tfc_web/transport/migrations/0031_auto_20180609_1655.py
- tfc_web/transport/migrations/0032_auto_20180610_1935.py
> map selectors in layout_config now have their own dedicated pop up that adapts to screen size and do not go off screen

- tfc_web/aq/templates/aq/aq_map.html
- tfc_web/aq/templates/aq/aq_plot.html
- tfc_web/csn/templates/csn/gateway.html
- tfc_web/csn/templates/csn/network_info.html
- tfc_web/parking/templates/parking/parking_map.html
- tfc_web/parking/templates/parking/parking_plot.html
- tfc_web/smartpanel/templates/smartpanel/displays.html
- tfc_web/smartpanel/templates/smartpanel/layout_config.html
- tfc_web/templates/bus_map_shadow.html
- tfc_web/templates/bus_route_map.html
- tfc_web/templates/bus_stop.html
- tfc_web/templates/leaflet_snippet.html
- tfc_web/templates/map_template.html
- tfc_web/templates/route_timetable_map.html
- tfc_web/traffic/templates/traffic/zone_map.html
- tfc_web/traffic/templates/traffic/zone_transit_plot.html
- tfc_web/traffic/templates/traffic/zones_map.html
- tfc_web/transport/templates/transport/bus_route_timetable_map.html
- tfc_web/transport/templates/transport/map_template.html
- tfc_web/transport/templates/transport/map_template_sirivm.html
- tfc_web/transport/templates/transport/vjrt.html
Use the opportunity to update to the last version
> Use everywhere the same version of leaflet

- tfc_web/traffic/templates/traffic/zone_map.html
- tfc_web/traffic/templates/traffic/zones_map.html
Note this PR is currently against jw35-replace-dataserver, pending its merge
Add map scale to the zone maps. This should probably be extended to other Leaflet-based maps in the syste.
> Add a scale control to maps

- tfc_web/traffic/templates/traffic/zone_map.html
- tfc_web/traffic/templates/traffic/zone_transit_plot.html
- tfc_web/traffic/templates/traffic/zones_map.html
- tfc_web/traffic/views.py
Improve the links in map pop ups, and add a ‘Reverse zone’ lint to graphs that have such a zone.
> Jw35 traffic page linkage

- tfc_web/templates/base.html
> Add a menu link to change password

- tfc_web/smartcambridge/admin.py
- tfc_web/smartcambridge/models.py
Add a __str__ method to SmartCambridgeUser, and add 'Accepted TCs'
to the list view in Django Admin.
> Make SmartCambridgeUser work better with Django Admin

- CHANGELOG.md
Add API documentation for (existing) transport API pagination
> Document transport api pagination

- CHANGELOG.md
Matching GitHub 'release' documentation
> Retrospectively update CHANGELOG for R10.0

- tfc_web/smartpanel/templates/smartpanel/pocket.html
Our free trial has expired and we don't want to pay.
> Drop Errorception logging

- tfc_web/transport/management/commands/update_bus_info.py
Closes https://github.com/SmartCambridge/tfc_web/issues/297
> Avoid script import failing when there is no description for a bus line

- tfc_web/transport/views.py
old code was mistakenly uncommented
Closes #309
> Timetables bugfix

- tfc_web/transport/views.py
> Add missing Http404 import and fix syntax

- tfc_web/transport/utils/transxchange.py
> Remove abbreviations from the timetable

- tfc_web/templates/about.html
- tfc_web/templates/base.html
- tfc_web/templates/index.html
...and update one URL that's changes and remove one link whose target
is lost in the mists of time.
> Fix some lurking City Deal references

- tfc_web/templates/base.html
> fix bug with location of sw.js
