- tfc_web/transport/management/commands/update_bus_info.py
OperatingProfile is optional according to the schema and at least one
current timetable file omits it. This patch allows for this and applies
the default (MondayToFriday) if it does.
This patch also adds logging of the file being processed to aid
diagnosing such problems in future.
A test run on tfc-app4 suggests that this patch works!
> Fix update_bus_info to cope with missing OperatingProfile element

- tfc_web/dashboard/templates/dashboard/station_board.html
- tfc_web/dashboard/urls.py
- tfc_web/dashboard/views.py
- tfc_web/requirements.txt
- tfc_web/static/dashboard/widgets/station_board/station_board.js
This patch ports the station_board widget to the Django framework. It's basically working, but needs fixes to #13 and #15 to display correctly.
Please can someone review this and merge it if appropriate.
> Ported station_board widget to Django framework

- tfc_web/transport/api/views.py
There are some rare cases where different buses have the same departure time and stop. In order to avoid returning more than one Journey as a result in the API, this modification allows the user of the API to also include the destination stop. This should avoid returning more than one Journey, as there is (at this moment) no cases where more than bus departs at the same time from the same stop with the same destination.
> Avoid returning two Journeys

- tfc_web/smartpanel/templates/smartpanel/info.html
> Fix the link to the NRE logo on the Smartpanel /info/ page

- tfc_web/smartpanel/templates/smartpanel/layout_config.html
- tfc_web/smartpanel/templates/smartpanel/layout_config2.html
- tfc_web/smartpanel/views/smartpanel.py
While it looked as if the framework was auto-discovering widgets, it
turns out:
1) That generate_widget_list() in smartpanel/views/smartpanel.py didn't
work; and
2) smartpanel/templates/smartpanel/layout_config.html and
smartpanel/templates/smartpanel/layout_config2.html had a hard-coded
list and didn't use the supplied value of 'widgets_list'
This patch fixes this.
> Fix widget auto-discovery

- tfc_web/static/smartpanel/widgets/message_area/message_area_schema.json
A hidden feature of brutusin:json-forms is that a string field
with '"format": "text"' will generate a text area for editing.
Use this for editing the message parameter of message_area.
Closes #58
> Edit message text in a text area

- redeploy.sh
- tfc_web/smartpanel/templates/smartpanel/layout.html
- tfc_web/smartpanel/templates/smartpanel/layout_config.html
- tfc_web/smartpanel/templates/smartpanel/layout_config2.html
- tfc_web/static/smartpanel/widgets/message_area/message_area.js
- tfc_web/static/smartpanel/widgets/message_area/requirements.json
- tfc_web/static/smartpanel/widgets/message_area/sanitize-html.js
- tfc_web/static/smartpanel/widgets/station_board/station_board.js
- tfc_web/static/smartpanel/widgets/station_board/station_board_schema.json
- tfc_web/static/smartpanel/widgets/stop_bus_map/stop_bus_map.js
- tfc_web/static/smartpanel/widgets/stop_timetable/stop_timetable.js
- tfc_web/static/smartpanel/widgets/traffic_map/traffic_map.js
This (mainly) fixes various XSS problems:
1. JavaScript escape the JSON representation of the widget configuration data when embedding it in HTML pages and use JSON.parse() to de-serialize in JavaScript. This reduces the possibility of rogue data breaking out either into the HTML interpretation context or into JavaScript execution context.
2. Use sanitize-html to allow some but not all HTML in the message in message_area (the only place we allow HTML markup in parameters)
3. Otherwise eliminate use of innerHTML() to further reduce the danger of unexpected XSS issues
Incidentally, this PR also 
1. Removes dependancy on jQuery by message_area (just 'cos)
2. Makes 'offset' optional when calling station_board (defaults to 0)
3. Removes un-used moustache rendering option in bus_timetable …
> Fixup various XSS issues

- tfc_web/static/smartpanel/widgets/iframe_area/iframe_area_schema.json
- tfc_web/static/smartpanel/widgets/message_area/message_area_schema.json
- tfc_web/static/smartpanel/widgets/station_board/station_board_schema.json
- tfc_web/static/smartpanel/widgets/stop_bus_map/stop_bus_map.js
- tfc_web/static/smartpanel/widgets/stop_bus_map/stop_bus_map_schema.json
- tfc_web/static/smartpanel/widgets/stop_timetable/stop_timetable.js
- tfc_web/static/smartpanel/widgets/stop_timetable/stop_timetable_schema.json
- tfc_web/static/smartpanel/widgets/traffic_map/traffic_map_schema.json
- tfc_web/static/smartpanel/widgets/twitter_timeline/twitter_timeline_schema.json
- tfc_web/static/smartpanel/widgets/weather/weather_schema.json
1. Always ask for lat/lng in that order
2. Re-word various titles and descriptions
3. Request codes in 'enum's where appropriate
4. Add useful defaults where appropriate (having observed that defaults usefully pre-populate form fields)
5. Add experimental support for "smartpanel:*" format specifications
Isolating map definitions into a self-contained object (so that we can apply "format" to it) results in a change to the structure of the parameters passed to the stop_busmap widget and so some minor changes within it.
Closes #72
> Tidy the schema files:

- tfc_web/smartpanel/views/widgets/station_board.py
- tfc_web/smartpanel/views/widgets/weather.py
Minor fixes to station_board and weather views:
* Code didn't allow for the possibility of a response containing no train
services. Fixes #88.
* Remove space from cache key. Apparently spaces a problematic if the Django cache framework is used with memcached. Even without memcached this results in repeated warnings in the logs. Replace remaining ' ' with '!'.  Fixes #87
* Reduce logging of raw weather data to DEBUG. Helps with #89
> Jw35 fix station board weather

- tfc_web/static/smartpanel/widgets/station_board/station_board.js
- tfc_web/static/smartpanel/widgets/weather/weather.js
This fixes a problem displaying these widgets on the configuration
screen.
Helps with (closes?) #81
> Convert internal URL references to absolute

- tfc_web/smartpanel/templates/smartpanel/layout.html
- tfc_web/smartpanel/templates/smartpanel/layout_config.html
- tfc_web/smartpanel/templates/smartpanel/layout_config_overlay.html
Add DEBUG global
Widgets can assume the existence of a "DEBUG" global which can contain
their name if they are to emit debug logs to consle.log() (see widget
spec under 'Widget JavaScript objects'). This global needs to be created
by the framework before instantiating widgets and this patch does so.
Also add some stuff missing from the (probably obsolete) layout-config_overlay.html
Closes #97
> Jw35 fix debug #97

- tfc_web/static/smartpanel/widgets.css
smartpannel.css redefines many ul/ol/li CSS properties for its
own purposes. This edit attempts to reset them to something like
default for the benefit of widgets (in particular message_area).
Values are based on Chrome defaults.
This is to some extent a stop-gap pending review of CSS usage
throughout the framework.
Closes #98
> Add additional widget styling to get ul/ol/li working

- tfc_web/smartpanel/templates/smartpanel/station_board.html
- tfc_web/static/smartpanel/smartpanel.css
- tfc_web/static/smartpanel/widgets.css
- tfc_web/static/smartpanel/widgets/stop_timetable/stop_timetable.js
widgets.css was unconditionally redefining h1, h2 and table which was
problematic for display of non-widget information on pages that included
widgets.css. Isolate those definitions so they only apply within
objects with the .widget class.
Further-further isolate the table definitions, which apply only
to timetables, to a .timetables class and add this as needed to
station_board.html and stop_timetable.js.
Add a knock-on change to smartpanel.css to re-establish
the font definition on the logo/credit header which was previously
'leaking' from widgets.css.
Rename display_multiline_render_dom as display_multiline_render
following the removal of display_multiline_render_moustache.
Remove a collection of outdated comments left over from the conversion
from moustache, replacing some with more …
> Further isolate CSS rules in widgets.css; Rationalise stop_timetable.j

- tfc_web/tfc_web/settings.py
In production (with DEBUG = False), Django only logs django.server
messages to the console and relies on django.utils.log.AdminEmailHandler
for everythign else. But since we haven't set ADMINS that doesn't do
anything, leaving us deaf/blind.
This patch attempts to modify Django's default log configuration (see
https://docs.djangoproject.com/en/2.0/topics/logging/#disabling-logging-configuration)
to enable console logging even when DEBUG = True *and* to log messages
from everything, not just Django modules.
It's seems to work, but may not be optimal. Suggestions welcome.
Helps with #18
> Add some default Django logging

- tfc_web/smartpanel/templates/smartpanel/base.html
- tfc_web/smartpanel/templates/smartpanel/display.html
- tfc_web/smartpanel/templates/smartpanel/displays.html
- tfc_web/smartpanel/templates/smartpanel/home.html
- tfc_web/smartpanel/templates/smartpanel/info.html
- tfc_web/smartpanel/urls.py
- tfc_web/smartpanel/views/smartpanel.py
This Pull Request is better reviewed commit by commit:
- Commit 41c05c1 renames some leftovers to the new terminology from "screen" to "display"
- Commit 7e2c230 hide public layouts options 
- Commit 410298d restricts access to layouts to only owners and superadmins
- Commit dc9f348 adds a couple of menu options, one principally to show smartpanels info page.
- Commit 099b741 protects the smartpanels home page to require login, otherwise it will show as an empty page. 
Part of issue #146 but not complete, will be complete when opt-in public option is implemented
> Changes to layouts

- tfc_web/transport/management/commands/update_bus_stops.py
We must keep them there in case we still have buses using them in the cache, so we need to keep them at least until we update the list of routes/buses.
They could also be deleted in the future by checking the last_modified field.
> Do not delete Stop objects ever

- tfc_web/static/smartpanel/widgets/stop_timetable/stop_timetable.js
Prevent timetables listing journeys that just terminate at the stop being displayed
At the same time, rewrite line name 'Universal U' to 'U'
> Suppress journeys that terminate at the displayed stop (and rewrite 'Universal U' to 'U')

- tfc_web/smartpanel/templates/smartpanel/weather.html
- tfc_web/smartpanel/views/widgets/weather.py
The Met Office API isn't all that reliable, in particular returning
data missing documented fields. Since each forecast is valid for multiple
days it makes sense to cache a 'last known good' version when we see one
and use that if whatever we are currently fetching is broken in any way.
Note that we still cache what we fetch (or an empty place holder if we
don't fetch anything) so even in an error condition we still only
hit the API once wvery 10 minuites for each forecast location requested.
> Fall back to 'last known good' forecast on error

- tfc_web/smartpanel/templates/smartpanel/base.html
- tfc_web/smartpanel/templates/smartpanel/layout.html
- tfc_web/templates/about.html
- tfc_web/templates/base.html
- tfc_web/templates/index.html
- tfc_web/templates/template.html
Fix various external references that have rotted in various places:
1) Fix link from Connecting Cambridge and Smart Cambridge logo to  www.connectingcambridgeshire.co.uk/smartcamb/ --> www.connectingcambridgeshire.co.uk/smart-cambridge/
2) Replace CityDeal logo with GCP logo and replace link http://www.gccitydeal.co.uk/citydeal/smart --> https://www.greatercambridge.org.uk/smart/
3) Replace @gccitydeal reference with new @GreaterCambs
> Fix broken links in multiple places

- tfc_web/transport/management/commands/update_bus_info.py
Add tnds_zone as a prefix to the route and journey patterns objects ids to avoid clashes between zones with the same ids for routes and journey patterns
> Route and Journey pattern clashes between tnds zones

- README.md
This file is used to set environment variables before
starting the tfc_web application in run.sh. It can be used
to override the default Django configuration module.
This edit adds a description of this to README.md
> Document the ~tfc_prod/tfc_web_envvars file

- tfc_web/requirements.txt
There's a security vulnerability in earlier versions
> Update requests version requirement

- tfc_web/csn/vertex_pg_migrations/0001_create_database.sql
- tfc_web/csn/vertex_pg_migrations/0001_reverse.sql
- tfc_web/csn/vertex_pg_migrations/0002_create_sensor_tables.sql
- tfc_web/csn/vertex_pg_migrations/0002_reverse.sql
- tfc_web/csn/vertex_pg_migrations/0003_create_table_csn_sensordata.sql
- tfc_web/csn/vertex_pg_migrations/0003_reverse.sql
- tfc_web/csn/vertex_pg_migrations/README.md
- tfc_web/tfc_web/settings_dev.py
There are two databases in production (default and tfcserver). Use only one with docker. Use the PR to also add the migrations necessary for the second database for the csn app from https://github.com/ijl20/vertx_pg for info.
> CSN: Only use one database in Docker (settings_dev)

- tfc_web/api/api_docs.py
- tfc_web/smartpanel/static/smartpanel/bus_stop_chooser/bus_stop_chooser.js
- tfc_web/transport/api/views.py
Due to the speed improvements achieved using the new PostGIS query in the Stops list API query, increase the maximum page size to 200 and increase the limit in the bus stop chooser.
> Change the Stops API query pagination

- tfc_web/csn/forms.py
Everynet NS API for devices accepts upper and lower case hex as values for its input parameters but then internally applies lowercase to all of them when storing this values in everynet's database. Its delete device API endpoint has a bug because it doesn't apply the same filter (lowercase all inputs) into its input parameters and thus causes 404 not found when using an uppercase hex as an input. This PR forces all webforms in CSN to store lowercase for all hex values in our database to avoid facing this bug in any of our API calls.
Closes #276
> Workaround for bug in everynet API

- tfc_web/csn/everynet_api.py
Supporting APP encryption requires a major refactor to do not ask the user for any of the keys.
> Do not yet support APP encryption

- tfc_web/smartpanel/static/smartpanel/widgets/iframe_area/iframe_area.css
It appears that a iframe defaults to 300pxx150px if not otherwise
set. This causes problems when including some content using the
iframe_area widget.
This edit forces it to 100%x100%
> Explicitly set height/width of iframe

- tfc_web/transport/views.py
This doesn't solve the problem but it avoids throwing an error. We need to make slug to be unique in the data model to avoid this occurring as the we won't be able to access to all those entries that have the same slug. This is an edge case, though.
Closes #301
> Avoid error when we have multiple entries with the same slug

- tfc_web/smartpanel/views/widgets/station_board.py
- tfc_web/smartpanel/views/widgets/weather.py
As with weather, arrange to cache the last known good station board
for a particular station and use that data if an attempt to retrieve
new information fails. As well as allowing station board widgets to
ride over outages of the underlying service, this will prevent
exceptions being thrown when this happens and so avoid torrents
of emails from the logging system.
Unlike weather, only cache last known good data for half an hour
since it will be stale after that.
Closes #302
> Rework station_board view to better cope with errors

- tfc_web/tfc_web/settings.py
- tfc_web/tfc_web/settings_production.py
Move the definition of the logger that causes emails to be sent
on errors from settings.py (which is used by everything) to
settings_production.py (which is used in production).
The intension is to stop emails being generated on development
machines (which are probably running with DEBUG=True and so will
show tracebacks anyway).
> Restrict emailing errors to production machines

- tfc_web/api/tests/.gitignore
- tfc_web/api/tests/test_api.py
- tfc_web/authmultitoken/serializers.py
- tfc_web/requirements.txt
There's an issue with the version of django-rest-framework that we are using - see here https://github.com/SmartCambridge/tfc_web/network/alert/tfc_web/requirements.txt/djangorestframework/open.
This PR updates DRF to at least 3.9.1, Django to at least 1.11.6 (due to an undocumented DRF dependancy) and fixes our dependancy on rest_framework.compat.authenticate() which was removed in DRF 3.9.0.
It also adds a simple smoke test of all the API endpoints to help testing this and similar upgrade in the future.
> Upgrade django-rest-framework

- tfc_web/parking/api/serializers.py
- tfc_web/parking/templates/parking/parking_plot.html
- tfc_web/parking/views.py
The capacity marker (red line and '(max xxxx)' wording) for the car parks comes from the static car park metadata which can't cope with changes to capacity over time.
By comparison, the list and the map pages get this information from the 'capacity' field of the occupancy record.
This edit changes the graph logic to use the capacity from the last occupancy record for the day being plotted. This still isn't quite right for a day on which the capacity changes or given decreasing capacity and prior_days plots, but since these are rare events it's not worth worrying about.
At the same time, drop `spaces_capacity` from car park metadata returned by the API - a single capacity entry can't reflect changes to capacity over time and while these are rare they do happen. So having this field is …
> Fix capacity annotation on car park graphs

- tfc_web/smartpanel/admin.py
- tfc_web/smartpanel/models.py
1) Improve Django admin for Smartpanels
Add useful fields and searching to the Django admin list display for
Smartpanel displays and layouts, in particular to make it easier
to find the owner of a particular panel.
Also add 'slug' to the result of `__str__` for displays since typically
the name is useless.
2) Use OSM for editing Smartpanel locations in Django admin
Without this edit, django.contrib.gis.db.models.PointField fields
are displayed on a low-res aerial view.
> Jw35 smartpanel admin 2

- tfc_web/docker-compose.yml
Add a new 'target' (or whatever they are called) to the docker-compose
script that will run './manage.py makemigrations' as a convenience
when changing database schemas.
This requires that the /usr/src/app volume is mounter read-write,
but fortunately it already is...
> Add new makemigrations target to docker-compose

- tfc_web/tfc_web/settings.py
This edit addresses a steady trickle of advertising spam on the forum
by requiring moderator approval for new posts. It works by removing
'can_post_without_approval' from the
MACHINA_DEFAULT_AUTHENTICATED_USER_FORUM_PERMISSIONS configuration
list.
Note that Machina doesn't alert administrators to the presence
of items awaiting moderation so someone needs to check the moderation
queue from time to time using the link on the forum front page.
> Require moderator approval for postings

- tfc_web/smartpanel/templates/smartpanel/pocketlog_total.html
- tfc_web/smartpanel/templates/smartpanel/pocketlog_unique.html
The graph pages were inheriting from base.html, rather then
smartpanel/base.html and so had the main site left-hand menu rather then
the one used on other SmartPanel pages. This was particularly silly because
the SmartPanel menu is the only place that links to the graphs appear.
This edit fixes this.
> Fix the menu on the Pocket SmartPanel usage graphs

- tfc_web/api/extractors/zone.py
- tfc_web/api/templates/api/zone-schema.html
- tfc_web/traffic/api/serializers.py
- tfc_web/traffic/templates/traffic/zone_transit_plot.html
- tfc_web/transport/api/views.py
1) Add details of the bus journey responsible for each zone completion to the response to the zone-->history API endpoint and to the zone data available in the download API. This data used to be available (at least internally) but wasn't included in the API as originally launched. This data has some utility (it supplies data about the service and timetable journey, for example, and it was
displayed in a popup on the zone transit graph)
Closes #203
2) Add (restore) journey details to the popup on the zone transit time graphs. This
functionality was lost in the move to the REST API because the API didn't include this data.
3) Allow the result of the transport-->journey API endpoint to optionally
be filtered by line name and/or operator. Helps to reduce the number of API calls
required if …
> Program api improvements

- tfc_web/aq/templates/aq/aq_plot.html
- tfc_web/parking/templates/parking/parking_plot.html
- tfc_web/traffic/templates/traffic/zone_transit_plot.html
The next/previous day/month navigation on the aq, parking and traffic
graphs pollutes browser history by adding two entries for each click -
one to the current URl with '#' appended, one to the wanted URL.
This edit stops this happening by arranging for the 'onclick' handler
to return 'false'.
[Yes, I know use of onclick= should be replaced by nicer DOM manipulation
but the approach in this edit is minimally invasive]
Closes #355
> Stop graph navigation polluting browser history

- tfc_web/api/extractors/btjourney.py
- tfc_web/traffic/api/views.py
For reasons unknown, the period field in journey data is occasionally
an empty object rather than an integer. In particular this has been
observed for very recently created links
(see e.g. this from CAMBRIDGE_JTMS|9800YRAA8RIZ on 2020-02-16):
```
{
"id": "CAMBRIDGE_JTMS|9800YRAA8RIZ",
"time": null,
"period": {},
"travelTime": null,
"normalTravelTime": null,
"ts": 1581858394
}
```
This causes the corresponding searilizer to complain. This fix overwrites
such valuse with None which searalizes as 'null' as expected.
> Work around period appearing as {} (empty object)

- tfc_web/api/views.py
The changes in 1def58b1 lost a call to sorted() around os.listdir(),
with the result that downloadable files appeared in directory order
rather than sorted by date. This edit restores the omission.
> Restore sorting of the list of downloadable files

- tfc_web/traffic/api/views.py
Without /media/tfc/btjourney the API is useless, but prior to this edit it caused internal server error if it was invoked when /media/tfc/btjourney was missing. This edit causes it to return either empty lists or Not Found errors as appropriate.
Fixes #367
> Defend btjourney API against absence of /media/tfc/btjourney
